### ISSUE TITLE
Do not build and link the examples

### ISSUE THREAD

**Issue by melroy89** [avocadoboi/cpp20-http-client#8]
I'm using your library via `FetchContent`. But it seems that the _examples_ folder is getting build & linked to my binary. I don't think this is wanted behavior. Maybe a simple CMake flag can help disabling building/linking the examples?

```
[build] [8/16   6% :: 5.183] Building CXX object _deps/cpp20httpclient-build/examples/CMakeFiles/example_get_request_simple.dir/get_request_simple.cpp.o
[build] [8/16  12% :: 5.218] Building CXX object _deps/cpp20httpclient-build/examples/CMakeFiles/example_socket.dir/socket.cpp.o
[build] [8/16  18% :: 5.587] Building CXX object _deps/cpp20httpclient-build/examples/CMakeFiles/example_async_get_request.dir/async_get_request.cpp.o
[build] [8/16  25% :: 5.601] Building CXX object _deps/cpp20httpclient-build/examples/CMakeFiles/example_post_request.dir/post_request.cpp.o
[build] [8/16  31% :: 6.318] Building CXX object _deps/cpp20httpclient-build/CMakeFiles/cpp20_http_client.dir/source/cpp20_http_client.cpp.o
[build] [9/16  37% :: 6.373] Linking CXX static library _deps/cpp20httpclient-build/lib/libcpp20_http_client.a
[build] [13/16  43% :: 6.555] Building CXX object CMakeFiles/project_name.dir/src/main.cpp.o
[build] [14/16  50% :: 6.555] Linking CXX executable _deps/cpp20httpclient-build/bin/example_socket
[build] [14/16  56% :: 6.632] Linking CXX executable _deps/cpp20httpclient-build/bin/example_get_request_simple
[build] [14/16  62% :: 6.634] Linking CXX executable _deps/cpp20httpclient-build/bin/example_post_request
[build] [14/16  68% :: 6.639] Linking CXX executable _deps/cpp20httpclient-build/bin/example_async_get_request
[build] [14/16  75% :: 6.754] Linking CXX executable binary_name
[build] [14/16  81% :: 6.941] Building CXX object _deps/cpp20httpclient-build/examples/CMakeFiles/example_get_request.dir/get_request.cpp.o
[build] [15/16  87% :: 7.071] Linking CXX executable _deps/cpp20httpclient-build/bin/example_get_request
[build] [15/16  93% :: 7.200] Building CXX object _deps/cpp20httpclient-build/examples/CMakeFiles/example_async_simple.dir/async_simple.cpp.o
[build] [16/16 100% :: 7.330] Linking CXX executable _deps/cpp20httpclient-build/bin/example_async_simple
```

**Comment by melroy89** [comment]
If you do not under stable what I mean, see this example: https://github.com/jarro2783/cxxopts/blob/master/CMakeLists.txt#L45

Which allows you to disable building examples (`CXXOPTS_BUILD_EXAMPLES`) and another option to disable building tests (`CXXOPTS_BUILD_TESTS`), etc. So the CMake project only builds and links what you want, like in my case I only want to build CPP20 Http Client without examples and without tests.

**Comment by melroy89** [comment]
OK. I introduced it myself: https://github.com/avocadoboi/cpp20-http-client/pull/9

**Comment by avocadoboi** [comment]
Hmm, I am not sure whether this is the solution. When you are building your project with CMake, the default target is `all`. If you do not want to build all targets, then specify which target you want to build, for example `cmake --build ./build --target my_project_using_cpp20_http_client`. When I do this, none of the examples or tests get built, only the library dependency of the executable target that I am building, and the executable itself. Adding flags to turn off building certain executables feels like it defeats the purpose of targets in modern CMake. However, I am not an expert on CMake so please correct me if I am missing something here. Regardless I am thankful for your efforts.

**Comment by melroy89** [comment]
I think you're right when I set the target to only build my binary, it seems that only your library gets build without the tests/examples.

That being said, it could not hurt anything if you want to create flexibility during the cmake generation process.
